// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbxfvavoiddsumbyezqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJieGZ2YXZvaWRkc3VtYnllenFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDIxMDMsImV4cCI6MjA2NjYxODEwM30.G7_hbxwCCdE-cZc7YucpFjZ9euH78hjoOPez3TS1CGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);